### ISSUE TITLE
Visualizing homography coordinates on the soccer overhead template 

### ISSUE THREAD

**Issue by harshap-ai** [SoccerNet/sn-gamestate#2]
Hello authors/curators, 

I have a couple of doubts about visualizing the homography coordinates on the overhead soccer pitch template:

1. I'm unsure where I can find the right template image, with the same resolution (I believe it should be 520p) as mentioned in the repo code. 
2. Does "bbox_pitch" in the .json annotations correspond to the homography coordinates? 

Thanks, 
Harish

**Comment by VlSomers** [comment]
Hi @harshap-ai, indeed the bbox_pitch corresponds to the coordinates of the bottom left/center/right of the image bounding box when projected on the pitch 2D coordinate space. I'm not sure I understood your first question, there is a template image here: "sn_gamestate/visualization/Radar.png". This image is an approximate of the real pitch. Let me know if it answers all your questions.

**Comment by harshap-ai** [comment]
Hello @VlSomers, thanks for your prompt reply! I wanted to visualize the homography coordinates on the projected space (which I believe is an overhead soccer field template image). I'm unsure how to do that and hence would appreciate if you can help with that.

**Comment by VlSomers** [comment]
Hello @harshap-ai, 2D pitch positions in the .json files are provided **in meters**, within a coordinate system having (0,0) as the pitch center, with the X axis along the length of the field and the Y axis along the width, with negative X corresponding to the left side of the pitch w.r.t. camera viewpoint. For the visualization, we make the assumption the pitch has a size of 105x68 meters (length x width). The pitch template image "sn_gamestate/visualization/Radar.png" has a size of 125x78 and depicts the pitch + borders around it. In this image, 1 pixel = 1 square meter. Let me know if it answers your questions.

**Comment by harshap-ai** [comment]
@VlSomers This clarifies my query. Thanks a lot!
