### ISSUE TITLE
why download dataset do not include annotation?

### ISSUE THREAD

**Issue by CarlHuangNuc** [SoccerNet/sn-gamestate#4]
i using this command to download dataset, but only include video.

from SoccerNet.Downloader import SoccerNetDownloader
mySoccerNetDownloader = SoccerNetDownloader(LocalDirectory="data/SoccerNetGS")
mySoccerNetDownloader.downloadDataTask(task="gamestate-2024",
                                       split=["train", "valid", "test", "challenge"])

**Comment by SilvioGiancola** [comment]
Our datasets contain annotations for the "train", "valid" and "test" sets. We do not provide annotations for the "challenge" set to prevent overfitting on that set.

**Comment by SilvioGiancola** [comment]
The zips have a file "sequence_info.json" that contains the GT
